bug: compiler crashes with segfault

The bug is observed on functions like
  def test(..., (a,b), ...) ...
i.e. an argument is a tuple that's given no type.

On the one hand, the compiler does not create a type for such an argument.

On the other hand, at least two places in the compiler expect all formals
to have *some* type because they run the code
  formal->type-> ...
without checking formal->type for NULL (e.g. hasGenericArgs() and resolve()).

I imagine that the right thing to do is to give the formal a type,
rather than patching all places that say 'formal->type->...' .
